# !!!
# Use this Dockerfile for deployment using the flyctl cli locally

FROM node:16.13.1-alpine

WORKDIR /app
COPY . .
COPY ./.env.prod ./.env
RUN npm ci

RUN npm run build

CMD ["npm", "run", "start:prod"]

