# This file is used for the CD pipeline on Github Actions
# It will automatically use the default Dockerfile for build

app = "pk-start"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  PORT = 8080
  PK_ENV = "production"
  PK_LOGIN_CODE_EXPIRY = 15
  PK_TOKEN_EXPIRY = "7d"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
